//! Shared types and persisted formats for Zeppelin's hierarchical IVF index.
//!
//! Hierarchical IVF is an approximate-nearest-neighbor (ANN) index that replaces
//! one large, flat centroid table with a tree of smaller centroid tables. A
//! query follows the closest centroids one level at a time, then scans selected
//! leaf clusters exactly or with quantized coarse ranking. Keeping several paths
//! at each level (the *beam*) improves recall at the cost of more object reads
//! and distance calculations.
//!
//! This module is the boundary shared by [`build`] and [`search`]. It defines
//! the JSON metadata object, the binary tree-node format, object-store key
//! conventions, and [`HierarchicalIndex`], the in-memory handle implementing
//! [`crate::index::VectorIndex`]. Leaf vector, attribute, bitmap, SQ8, and PQ
//! artifacts deliberately reuse the IVF-Flat formats.
//!
//! ```text
//! manifest-visible hierarchical segment
//!                 |
//!                 v
//!        tree_meta.json (root id, shape, encoding)
//!                 |
//!                 v
//!          node_<root>.bin
//!          /             \
//!   node_<child>.bin    numeric leaf-cluster id
//!          |                     |
//!          +----------+----------+
//!                     v
//!       cluster_N.bin + attrs_N.bin
//!       (+ bitmap/SQ8/PQ sidecars when configured)
//! ```
//!
//! Objects under a segment prefix are immutable build outputs. Their existence
//! in S3 or MinIO does **not** make the segment visible: the namespace manifest
//! remains authoritative, and the compaction layer publishes the completed
//! segment separately. Memory and local disk may cache these immutable bytes,
//! but neither cache can establish visibility.
//!
//! ## Reading map
//!
//! 1. Start with [`TreeMeta`] to understand the persisted tree description.
//! 2. Read [`TreeNode`] and [`serialize_tree_node`] for the per-node artifact.
//! 3. Read [`build::build_hierarchical`] for bottom-up construction.
//! 4. Read [`search::search_hierarchical`] for mixed-depth beam traversal and
//!    leaf reranking.
//! 5. Use [`HierarchicalIndex::load`] for the metadata-only query entry point.
//!
//! ## Invariants
//!
//! - Every centroid and its child identifier occupy the same position.
//! - Numeric child identifiers name leaf clusters; generated non-numeric IDs
//!   name tree-node objects. Mixed-depth nodes can contain both kinds.
//! - All centroids and vectors in one segment use [`TreeMeta::dim`].
//! - Persisted tree and leaf artifacts are write-once. Only a manifest update
//!   can make the completed segment visible to queries.
//! - Increasing the beam width explores more branches and normally improves
//!   recall, but also increases reads, bytes, CPU, and potentially latency.
//!
//! ## Rust concepts used here
//!
//! [`TreeMeta`] uses serde derives because it is a versioned JSON artifact;
//! `#[serde(default)]` keeps older metadata readable when embedded SQ8
//! calibration is absent. Java might use a JSON DTO with a nullable field, and
//! C would require an explicit decoder and presence flag. Rust's
//! [`Option`] makes the two format states explicit.
//!
//! The async trait implementation is generated by `async_trait`. It lets the
//! common index interface expose asynchronous object-store work even though
//! stable Rust traits do not directly provide object-safe `async fn` methods in
//! the way a Java interface returns `CompletableFuture`. Borrowed slices and
//! strings keep large vector batches and key components under caller ownership;
//! unlike C pointers, those borrows are non-null and lifetime checked.

/// Builds immutable hierarchical tree and leaf artifacts with recursive k-means.
pub mod build;
/// Navigates the centroid tree and ranks selected leaf-cluster rows.
pub mod search;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::config::IndexingConfig;
use crate::error::Result;
use crate::index::quantization::QuantizationType;
use crate::index::VectorIndex;
use crate::namespace::branching::ArtifactOrigin;
use crate::storage::ZeppelinStore;
use crate::types::{DistanceMetric, Filter, SearchResult, VectorEntry};
use crate::wal::manifest::immutable_artifact_cache_key;

/// Persisted description needed to open a hierarchical segment.
///
/// The builder writes this value as `tree_meta.json` after constructing tree
/// nodes and leaf artifacts. Loading it proves that the metadata object exists;
/// it does not prove manifest visibility. The namespace manifest is the
/// authoritative list of queryable segments.
///
/// Cloning this value duplicates owned strings and calibration bytes. Serde's
/// JSON representation is a compatibility boundary, so field meaning and
/// defaults must remain stable for already-written segments.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TreeMeta {
    /// Greatest depth recorded during construction; one denotes a root that
    /// points directly to leaf clusters.
    pub num_levels: usize,
    /// Requested maximum centroids per internal node.
    ///
    /// Empty k-means partitions are omitted, so an individual node may have
    /// fewer children than this target.
    pub branching_factor: usize,
    /// Number of source vectors represented by all leaf clusters.
    pub total_vectors: usize,
    /// Required component count for every stored vector, centroid, and query.
    pub dim: usize,
    /// Non-numeric identifier used to construct the root node's object key.
    pub root_node_id: String,
    /// Count of globally numbered leaf clusters, with valid IDs in
    /// `0..num_leaf_clusters`.
    pub num_leaf_clusters: usize,
    /// Coarse encoding used before full-precision reranking at leaf level.
    pub quantization: QuantizationType,
    /// Serialized SQ8 calibration embedded by current scalar-quantized builds.
    ///
    /// Older tree metadata omits this field and scalar search falls back to
    /// `sq_calibration.bin`.
    #[serde(default)]
    pub sq_calibration: Option<Vec<u8>>,
}

/// One immutable centroid-routing node stored as a binary object.
///
/// Each centroid routes to the child identifier at the same vector position.
/// Numeric identifiers refer to IVF-compatible leaf clusters; non-numeric IDs
/// refer to other [`TreeNode`] objects. An uneven k-means split can create a
/// mixed-depth node containing both kinds. In that state `is_leaf` is `false`,
/// and search recognizes the numeric children individually.
#[derive(Debug, Clone)]
pub struct TreeNode {
    /// Routing centroids in the segment's fixed vector dimension.
    pub centroids: Vec<Vec<f32>>,
    /// Positionally aligned node IDs or decimal leaf-cluster indexes.
    pub children: Vec<String>,
    /// Whether every child is a leaf cluster rather than another tree node.
    pub is_leaf: bool,
}

/// Lightweight in-memory handle to one immutable hierarchical segment.
///
/// Only [`TreeMeta`] and key-building context are held eagerly. Search fetches
/// tree nodes and selected leaf artifacts lazily through the optional tiered
/// cache. `bitmap_fields` comes from the manifest-facing query layer; a direct
/// metadata load leaves it empty and therefore uses exact attribute filtering.
///
/// Cloning the handle clones its owned metadata and strings; it does not clone
/// remote segment data or share mutable index state.
#[derive(Debug, Clone)]
pub struct HierarchicalIndex {
    /// Persisted tree shape, vector count, dimension, and leaf encoding.
    pub(crate) meta: TreeMeta,
    /// Namespace prefix used only to derive immutable object-store keys.
    pub(crate) namespace: String,
    /// Physical namespace owning the immutable tree and leaf artifacts.
    pub(crate) physical_namespace: String,
    /// Incarnation-qualified owner used to prevent disposable-cache aliasing.
    pub(crate) physical_origin: Option<ArtifactOrigin>,
    /// Manifest segment identifier used only to derive object-store keys.
    pub(crate) segment_id: String,
    /// Manifest-declared fields whose leaf clusters may have bitmap sidecars.
    pub(crate) bitmap_fields: Vec<String>,
    /// Exact routing-node identifiers written by this build.
    ///
    /// Metadata-only loads of legacy segments leave this empty. Manifest
    /// publication records the populated build-time inventory so receipts and
    /// clones root every lazily fetched internal node.
    pub(crate) routing_node_ids: Vec<String>,
}

// ---------------------------------------------------------------------------
// S3 key helpers
// ---------------------------------------------------------------------------

/// Constructs the object-store key for a segment's hierarchical metadata.
///
/// # Parameters
///
/// - `namespace`: Already-validated namespace key prefix.
/// - `segment_id`: Immutable segment identifier under that namespace.
///
/// # Returns
///
/// An owned key ending in `tree_meta.json`.
///
/// # Examples
///
/// Namespace `images` and segment `01ABC` produce
/// `images/segments/01ABC/tree_meta.json`.
pub fn tree_meta_key(namespace: &str, segment_id: &str) -> String {
    format!("{namespace}/segments/{segment_id}/tree_meta.json")
}

/// Constructs the object-store key for one binary routing node.
///
/// # Parameters
///
/// - `namespace`: Already-validated namespace key prefix.
/// - `segment_id`: Immutable segment identifier.
/// - `node_id`: Generated non-numeric routing-node identifier.
///
/// # Returns
///
/// An owned key ending in `node_<node_id>.bin`.
///
/// # Examples
///
/// Node `root` in segment `seg_1` becomes
/// `ns/segments/seg_1/node_root.bin`.
pub fn tree_node_key(namespace: &str, segment_id: &str, node_id: &str) -> String {
    format!("{namespace}/segments/{segment_id}/node_{node_id}.bin")
}

// Leaf-level cluster data reuses IVF-Flat keys:
//   cluster_{i}.bin, attrs_{i}.bin, sq_cluster_{i}.bin, etc.

// ---------------------------------------------------------------------------
// Node serialization
// ---------------------------------------------------------------------------

/// Encodes one routing node in Zeppelin's compact little-endian format.
///
/// The caller supplies the common segment dimension because it is persisted in
/// each node header. The function does not validate that every centroid has
/// exactly that dimension or that the child count matches the centroid count;
/// builders must preserve those invariants before calling it.
///
/// # Parameters
///
/// - `node`: Borrowed routing node whose centroids and child IDs are encoded in
///   their existing order.
/// - `dim`: Declared component count for each centroid.
///
/// # Returns
///
/// Owned immutable bytes with the following layout:
/// ```text
/// [num_centroids: u32 LE]
/// [dim: u32 LE]
/// [is_leaf: u8]
/// For each centroid: [f32 LE] * dim
/// For each child:    [id_len: u32 LE][id_bytes]
/// ```
///
/// # Examples
///
/// A two-dimensional leaf with one centroid and child `42` encodes a header,
/// two `f32` values, then the length and UTF-8 bytes for `42`.
///
/// # Rust Notes for Java/C Engineers
///
/// `&TreeNode` is a read-only borrow, similar to a Java reference used without
/// mutation or a C `const TreeNode *`, but Rust proves it is non-null and valid
/// for the call. Converting the final `Vec<u8>` into [`bytes::Bytes`] moves the
/// allocation into a cheaply cloneable immutable buffer rather than copying it.
pub fn serialize_tree_node(node: &TreeNode, dim: usize) -> bytes::Bytes {
    let n = node.centroids.len();
    let mut buf = Vec::new();

    buf.extend_from_slice(&(n as u32).to_le_bytes());
    buf.extend_from_slice(&(dim as u32).to_le_bytes());
    buf.push(if node.is_leaf { 1 } else { 0 });

    for centroid in &node.centroids {
        for &val in centroid {
            buf.extend_from_slice(&val.to_le_bytes());
        }
    }

    for child_id in &node.children {
        let id_bytes = child_id.as_bytes();
        buf.extend_from_slice(&(id_bytes.len() as u32).to_le_bytes());
        buf.extend_from_slice(id_bytes);
    }

    bytes::Bytes::from(buf)
}

/// Decodes and validates one binary routing-node object.
///
/// Header arithmetic is checked before capacities are allocated, preventing a
/// corrupt object from using wrapped sizes or requesting memory based on an
/// impossible centroid count. Child bytes use lossy UTF-8 conversion, matching
/// the current persisted-format behavior; invalid sequences become replacement
/// characters rather than a decoding error. Trailing bytes are ignored.
///
/// # Parameters
///
/// - `data`: Borrowed complete node-object bytes.
///
/// # Returns
///
/// An owned [`TreeNode`] containing exactly the centroid and child counts stated
/// by the header.
///
/// # Errors
///
/// Returns an index or serialization error for a short header, overflowing or
/// impossible dimensions, truncated centroid data, or truncated child IDs. No
/// state is mutated before an error is returned.
///
/// # Performance
///
/// Performs one linear pass over the bytes and allocates owned vectors and
/// child strings. It performs no object-store request itself.
///
/// # Examples
///
/// Bytes emitted by [`serialize_tree_node`] round-trip to an equivalent node.
/// A nine-byte header claiming billions of centroid values fails before a huge
/// allocation is attempted.
///
/// # Rust Notes for Java/C Engineers
///
/// Checked integer combinators and `Result` propagation replace the manual
/// overflow/status checks common in C. Java bounds checks would prevent raw
/// memory corruption, but could still allocate from an untrusted header unless
/// the same size validation were written explicitly. Returned vectors own their
/// data, so no pointer into `data` can outlive the input slice.
pub fn deserialize_tree_node(data: &[u8]) -> Result<TreeNode> {
    use crate::error::ZeppelinError;

    if data.len() < 9 {
        return Err(ZeppelinError::Index(
            "tree node blob too small for header".into(),
        ));
    }

    let n = u32::from_le_bytes(
        data[0..4]
            .try_into()
            .map_err(|_| ZeppelinError::Serialization("tree node header parse error".into()))?,
    ) as usize;
    let dim = u32::from_le_bytes(
        data[4..8]
            .try_into()
            .map_err(|_| ZeppelinError::Serialization("tree node header parse error".into()))?,
    ) as usize;
    let is_leaf = data[8] != 0;

    // Validate the header against the actual blob size before allocating:
    // n centroids of dim f32s plus n child-id length prefixes must fit.
    let min_size = n
        .checked_mul(dim)
        .and_then(|v| v.checked_mul(4))
        .and_then(|v| v.checked_add(n.checked_mul(4)?))
        .and_then(|v| v.checked_add(9))
        .ok_or_else(|| {
            ZeppelinError::Index(format!("tree node header size overflows: n={n}, dim={dim}"))
        })?;
    if min_size > data.len() {
        return Err(ZeppelinError::Index(format!(
            "tree node blob too small: header claims n={n}, dim={dim} (needs >= {min_size} bytes), got {}",
            data.len()
        )));
    }

    let mut offset = 9;

    // Read centroids.
    let mut centroids = Vec::with_capacity(n);
    for _ in 0..n {
        let end = offset + dim * 4;
        if end > data.len() {
            return Err(ZeppelinError::Index(
                "tree node blob truncated at centroid data".into(),
            ));
        }
        let mut c = Vec::with_capacity(dim);
        for _ in 0..dim {
            let val = f32::from_le_bytes(data[offset..offset + 4].try_into().map_err(|_| {
                ZeppelinError::Serialization("tree node centroid parse error".into())
            })?);
            c.push(val);
            offset += 4;
        }
        centroids.push(c);
    }

    // Read child IDs.
    let mut children = Vec::with_capacity(n);
    for _ in 0..n {
        if offset + 4 > data.len() {
            return Err(ZeppelinError::Index(
                "tree node blob truncated at child id".into(),
            ));
        }
        let id_len =
            u32::from_le_bytes(data[offset..offset + 4].try_into().map_err(|_| {
                ZeppelinError::Serialization("tree node child id parse error".into())
            })?) as usize;
        offset += 4;
        if offset + id_len > data.len() {
            return Err(ZeppelinError::Index(
                "tree node blob truncated at child id bytes".into(),
            ));
        }
        let id = String::from_utf8_lossy(&data[offset..offset + id_len]).into_owned();
        offset += id_len;
        children.push(id);
    }

    Ok(TreeNode {
        centroids,
        children,
        is_leaf,
    })
}

impl HierarchicalIndex {
    #[must_use]
    pub(crate) fn artifact_cache_key(&self, store_key: &str) -> String {
        self.physical_origin.as_ref().map_or_else(
            || store_key.to_string(),
            |origin| immutable_artifact_cache_key(origin, store_key),
        )
    }
    /// Returns the number of globally numbered leaf clusters.
    ///
    /// # Returns
    ///
    /// The persisted count from [`TreeMeta`]; valid cluster IDs are below it.
    pub fn num_leaf_clusters(&self) -> usize {
        self.meta.num_leaf_clusters
    }

    /// Returns the namespace key prefix borrowed from this handle.
    ///
    /// # Returns
    ///
    /// A string slice valid as long as the shared borrow of `self`.
    pub fn namespace(&self) -> &str {
        &self.namespace
    }

    /// Returns the immutable segment identifier borrowed from this handle.
    ///
    /// # Returns
    ///
    /// A string slice used with [`tree_meta_key`] and [`tree_node_key`].
    pub fn segment_id(&self) -> &str {
        &self.segment_id
    }

    /// Borrow the exact routing-node inventory produced by this build.
    #[must_use]
    pub(crate) fn routing_node_ids(&self) -> &[String] {
        &self.routing_node_ids
    }

    /// Loads an existing hierarchical index handle from its metadata object.
    ///
    /// This is a convenience wrapper around [`build::load_hierarchical`]. When
    /// a cache is supplied, `tree_meta.json` follows memory → disk → S3 lookup
    /// and is scoped-pinned after a successful fetch. Tree nodes and leaf data
    /// remain lazy.
    ///
    /// # Parameters
    ///
    /// - `store`: Object-store abstraction used on a cache miss.
    /// - `namespace`: Namespace containing the manifest-selected segment.
    /// - `segment_id`: Identifier of that immutable segment.
    /// - `cache`: Optional shared tiered cache. Cloning its [`std::sync::Arc`]
    ///   is unnecessary because this function only borrows it.
    ///
    /// # Returns
    ///
    /// A metadata-only index handle. Its bitmap field list is initially empty;
    /// the query layer fills it from manifest metadata when applicable.
    ///
    /// # Errors
    ///
    /// Propagates cache, object-store, or JSON decoding failures. It does not
    /// construct a default index when metadata is missing or corrupt.
    ///
    /// # Side Effects
    ///
    /// May populate cache tiers and replaces the namespace's scoped metadata
    /// pin after a successful load.
    ///
    /// # Consistency
    ///
    /// Callers must obtain `segment_id` from the authoritative manifest. Loading
    /// an arbitrary prefix does not make it visible.
    ///
    /// # Performance
    ///
    /// Reads one small JSON object on a cold miss; a warm cache avoids the
    /// object-store GET.
    ///
    /// # Examples
    ///
    /// Query planning reads a manifest-visible hierarchical segment, loads its
    /// metadata once, then lets beam search fetch only the visited nodes.
    pub async fn load(
        store: &ZeppelinStore,
        namespace: &str,
        segment_id: &str,
        cache: Option<&std::sync::Arc<crate::cache::DiskCache>>,
    ) -> Result<Self> {
        build::load_hierarchical(store, namespace, segment_id, cache).await
    }

    /// Loads a manifest-selected hierarchical segment from its physical owner.
    pub(crate) async fn load_from_located_manifest(
        store: &ZeppelinStore,
        located: crate::wal::manifest::LocatedSegmentRef<'_>,
        cache: Option<&std::sync::Arc<crate::cache::DiskCache>>,
    ) -> Result<Self> {
        build::load_hierarchical_from_located_manifest(store, located, cache).await
    }
}

#[async_trait]
impl VectorIndex for HierarchicalIndex {
    /// Builds the hierarchical artifacts required by the common index trait.
    ///
    /// See [`build::build_hierarchical`] for validation, partial-write, and
    /// publication-boundary details.
    async fn build(
        vectors: &[VectorEntry],
        config: &IndexingConfig,
        store: &ZeppelinStore,
        namespace: &str,
        segment_id: &str,
    ) -> Result<Self> {
        build::build_hierarchical(vectors, config, store, namespace, segment_id).await
    }

    /// Searches through the common trait with `nprobe` interpreted as beam width.
    ///
    /// Filtered calls use an oversampling factor of three, bypass the optional
    /// cache, and include attributes in returned results. The query layer calls
    /// [`search::search_hierarchical`] directly when it needs cache and response
    /// projection controls.
    async fn search(
        &self,
        query: &[f32],
        top_k: usize,
        nprobe: usize,
        filter: Option<&Filter>,
        distance_metric: DistanceMetric,
        store: &ZeppelinStore,
    ) -> Result<Vec<SearchResult>> {
        let oversample_factor = if filter.is_some() { 3 } else { 1 };
        search::search_hierarchical(
            self,
            query,
            top_k,
            nprobe,
            filter,
            distance_metric,
            store,
            oversample_factor,
            None,
            true,
        )
        .await
    }

    /// Returns the vector count recorded in persisted tree metadata.
    fn vector_count(&self) -> usize {
        self.meta.total_vectors
    }

    /// Returns the required query dimension recorded in tree metadata.
    fn dimension(&self) -> usize {
        self.meta.dim
    }
}

#[allow(clippy::unwrap_used, clippy::expect_used)]
#[cfg(test)]
mod tests {
    //! Format tests protecting hierarchical metadata and node compatibility.

    use super::*;

    /// Proves an internal node preserves centroid order, child IDs, and kind.
    #[test]
    fn test_tree_node_serde_roundtrip_internal() {
        let node = TreeNode {
            centroids: vec![vec![1.0, 2.0, 3.0], vec![4.0, 5.0, 6.0]],
            children: vec!["node_a".to_string(), "node_b".to_string()],
            is_leaf: false,
        };
        let data = serialize_tree_node(&node, 3);
        let decoded = deserialize_tree_node(&data).unwrap();
        assert_eq!(decoded.centroids, node.centroids);
        assert_eq!(decoded.children, node.children);
        assert!(!decoded.is_leaf);
    }

    /// Proves a numeric leaf-cluster child survives the binary round trip.
    #[test]
    fn test_tree_node_serde_roundtrip_leaf() {
        let node = TreeNode {
            centroids: vec![vec![0.5, 0.5]],
            children: vec!["42".to_string()],
            is_leaf: true,
        };
        let data = serialize_tree_node(&node, 2);
        let decoded = deserialize_tree_node(&data).unwrap();
        assert_eq!(decoded.centroids, node.centroids);
        assert_eq!(decoded.children, node.children);
        assert!(decoded.is_leaf);
    }

    /// Rejects a blob too short to contain the fixed nine-byte header.
    #[test]
    fn test_tree_node_deserialize_truncated() {
        let data = vec![0u8; 5]; // too small
        assert!(deserialize_tree_node(&data).is_err());
    }

    /// Protects against allocating from a corrupt, enormous centroid count.
    #[test]
    fn test_tree_node_deserialize_huge_header() {
        // Fuzz regression: header claims ~4 billion centroids, which drove a
        // ~96 GB Vec::with_capacity before any bounds check.
        let data = [10, 0, 1, 239, 1, 0, 1, 239, 0, 0, 0];
        assert!(deserialize_tree_node(&data).is_err());
    }

    /// Protects checked header-size arithmetic from multiplication overflow.
    #[test]
    fn test_tree_node_deserialize_header_size_overflow() {
        // n * dim * 4 overflows; must error, not wrap.
        let mut data = Vec::new();
        data.extend_from_slice(&u32::MAX.to_le_bytes()); // n
        data.extend_from_slice(&u32::MAX.to_le_bytes()); // dim
        data.push(0);
        assert!(deserialize_tree_node(&data).is_err());
    }

    /// Proves JSON metadata retains routing, shape, and segment-count fields.
    #[test]
    fn test_tree_meta_serde_roundtrip() {
        let meta = TreeMeta {
            num_levels: 3,
            branching_factor: 100,
            total_vectors: 1_000_000,
            dim: 128,
            root_node_id: "root".to_string(),
            num_leaf_clusters: 10_000,
            quantization: QuantizationType::None,
            sq_calibration: None,
        };
        let json = serde_json::to_string(&meta).unwrap();
        let back: TreeMeta = serde_json::from_str(&json).unwrap();
        assert_eq!(back.num_levels, 3);
        assert_eq!(back.branching_factor, 100);
        assert_eq!(back.total_vectors, 1_000_000);
        assert_eq!(back.root_node_id, "root");
        assert_eq!(back.num_leaf_clusters, 10_000);
    }

    /// Locks the stable object-key layout used by build, query, cache, and GC.
    #[test]
    fn test_s3_key_helpers() {
        assert_eq!(
            tree_meta_key("ns1", "seg_001"),
            "ns1/segments/seg_001/tree_meta.json"
        );
        assert_eq!(
            tree_node_key("ns1", "seg_001", "root"),
            "ns1/segments/seg_001/node_root.bin"
        );
    }
}
