//! Commented `zeppelin.toml` rendering and fail-before-write validation.
//!
//! [`render_and_validate`] generates a fresh enforced-mode cursor secret when
//! required, parses the exact rendered bytes through
//! [`Config::load_from_str`], and cross-checks the parsed result against the
//! tuning intent. [`write_validated_config`] accepts only that validated
//! wrapper, preventing callers from accidentally writing unchecked text.

use std::fs::OpenOptions;
use std::io::Write;
use std::path::{Path, PathBuf};

use rand::{rngs::OsRng, RngCore};
use thiserror::Error;

use crate::config::{Config, SecurityMode, StorageBackend};
use crate::error::ZeppelinError;
use crate::index::quantization::QuantizationType;

use super::catalog::Cloud;
use super::tuner::{SecurityChoice, TunedKnobs};

/// Rendering, validation, intent-checking, or file-output failure.
#[derive(Debug, Error)]
pub enum EmitError {
    /// The real configuration loader rejected the rendered bytes.
    #[error("rendered configuration failed validation: {0}")]
    Config(#[from] ZeppelinError),
    /// Parsed values do not match the values the tuner intended to emit.
    #[error("rendered configuration failed intent cross-check: {reason}")]
    IntentMismatch {
        /// Exact mismatched invariant.
        reason: String,
    },
    /// The destination already exists and force was not selected.
    #[error("refusing to overwrite existing config {path}; pass --force to replace it")]
    AlreadyExists {
        /// Existing destination.
        path: PathBuf,
    },
    /// The validated bytes could not be written.
    #[error("failed to write config {path}: {source}")]
    Io {
        /// Intended destination.
        path: PathBuf,
        /// Operating-system failure.
        #[source]
        source: std::io::Error,
    },
}

/// Exact rendered bytes paired with their validated parsed representation.
pub struct ValidatedConfig {
    text: String,
    config: Config,
}

impl ValidatedConfig {
    /// Exact TOML bytes safe to write.
    #[must_use]
    pub fn text(&self) -> &str {
        &self.text
    }

    /// Parsed and fully validated configuration used for the intent check.
    #[must_use]
    pub fn config(&self) -> &Config {
        &self.config
    }
}

/// Renders a commented standalone `zeppelin.toml` from tuned values.
///
/// Enforced security mode receives a fresh random 256-bit cursor HMAC key on
/// every call. The key is deliberately rendered only into the returned TOML;
/// it is never logged or exposed by [`Config`]'s debug representation.
#[must_use]
pub fn render_toml(knobs: &TunedKnobs) -> String {
    let mut output = String::new();
    push_line(
        &mut output,
        "# Generated by zeppelin_advisor. Review before production rollout.",
    );
    push_line(
        &mut output,
        "# Validation intentionally excludes environment overrides; env still wins at boot.",
    );
    push_line(
        &mut output,
        &format!(
            "# Selection: {} / {} / {} x{} / {}",
            knobs.cloud.name(),
            knobs.region,
            knobs.instance_name,
            knobs.replicas,
            knobs.cache.label()
        ),
    );
    push_line(
        &mut output,
        &format!(
            "# Shape: {} vectors x {} dims; {:.3} GB estimated at rest; p99 {:.2} ms.",
            knobs.shape.vectors, knobs.shape.dims, knobs.dataset_storage_gb, knobs.predicted_p99_ms
        ),
    );
    push_line(
        &mut output,
        &format!(
            "# Canonical IVF nlist is {}; defaults remain scale-aware rather than hardcoding nlist.",
            knobs.nlist
        ),
    );
    push_line(&mut output, "");

    push_line(&mut output, "[storage]");
    push_line(
        &mut output,
        &format!("backend = {}", toml_quote(storage_backend(knobs.cloud))),
    );
    push_line(
        &mut output,
        &format!("bucket = {}", toml_quote(&knobs.bucket)),
    );
    if knobs.cloud == Cloud::Aws {
        push_line(
            &mut output,
            &format!("s3_region = {}", toml_quote(&knobs.region)),
        );
    } else {
        push_line(
            &mut output,
            "# Region is a placement/pricing choice; this backend obtains it from provider configuration.",
        );
    }
    push_line(&mut output, "fail_fast = true");
    push_line(&mut output, "");

    push_line(&mut output, "[server]");
    push_line(
        &mut output,
        &format!(
            "max_concurrent_queries = {} # 8 x vCPU, capped by the hardcoded 64-connection S3 pool",
            knobs.max_concurrent_queries
        ),
    );
    push_line(
        &mut output,
        &format!("max_request_body_mb = {}", knobs.max_request_body_mb),
    );
    push_line(
        &mut output,
        &format!(
            "request_timeout_secs = {} # >= ceil(3 x predicted p99)",
            knobs.request_timeout_secs
        ),
    );
    push_line(&mut output, "");

    push_line(&mut output, "[cache]");
    push_line(
        &mut output,
        &format!(
            "dir = {}",
            toml_quote(&knobs.cache_dir.display().to_string())
        ),
    );
    push_line(
        &mut output,
        &format!("max_size_gb = {}", knobs.cache_max_size_gb),
    );
    push_line(
        &mut output,
        &format!("memory_cache_max_mb = {}", knobs.memory_cache_max_mb),
    );
    push_line(
        &mut output,
        &format!(
            "wal_fragment_cache_max_mb = {}",
            knobs.wal_fragment_cache_max_mb
        ),
    );
    push_line(
        &mut output,
        &format!(
            "decoded_artifact_cache_max_mb = {}",
            knobs.decoded_artifact_cache_max_mb
        ),
    );
    push_line(
        &mut output,
        &format!("manifest_cache_ttl_ms = {}", knobs.manifest_cache_ttl_ms),
    );
    push_line(
        &mut output,
        &format!(
            "namespace_registry_ttl_ms = {}",
            knobs.namespace_registry_ttl_ms
        ),
    );
    push_line(&mut output, "hydration_enabled = true");
    push_line(
        &mut output,
        &format!("hydration_parallelism = {}", knobs.hydration_parallelism),
    );
    push_line(
        &mut output,
        &format!(
            "hydration_max_segment_fraction = {:.1}",
            knobs.hydration_max_segment_fraction
        ),
    );
    push_line(&mut output, "");

    push_line(&mut output, "[indexing]");
    push_line(&mut output, &format!("default_nprobe = {}", knobs.nprobe));
    push_line(&mut output, &format!("max_nprobe = {}", knobs.max_nprobe));
    push_line(
        &mut output,
        &format!(
            "quantization = {}",
            toml_quote(quantization_name(knobs.quantization))
        ),
    );
    if knobs.quantization == QuantizationType::Product {
        push_line(&mut output, &format!("pq_m = {}", knobs.pq_m));
    }
    push_line(
        &mut output,
        &format!("bitmap_index = {}", knobs.shape.filters),
    );
    push_line(&mut output, &format!("fts_index = {}", knobs.shape.fts));
    push_line(
        &mut output,
        &format!(
            "bm25_max_full_scan_vectors = {}",
            knobs.bm25_max_full_scan_vectors
        ),
    );
    push_line(&mut output, "");

    push_line(&mut output, "[compaction]");
    push_line(
        &mut output,
        &format!(
            "max_wal_bytes_before_compact = {}",
            knobs.max_wal_bytes_before_compact
        ),
    );
    push_line(&mut output, "");

    push_line(&mut output, "[query]");
    push_line(
        &mut output,
        &format!(
            "rerank_coalesce_gap_bytes = {} # [M] real object stores favor fewer GETs",
            knobs.rerank_coalesce_gap_bytes
        ),
    );
    push_line(&mut output, "");

    push_line(&mut output, "[gc]");
    push_line(
        &mut output,
        &format!(
            "horizon_secs = {} # computed floor {}; never uses allow_unsafe_short_horizon",
            knobs.gc_horizon_secs, knobs.gc_horizon_floor_secs
        ),
    );
    push_line(
        &mut output,
        &format!(
            "compaction_upload_window_secs = {}",
            knobs.compaction_upload_window_secs
        ),
    );
    push_line(
        &mut output,
        &format!("skew_slop_secs = {}", knobs.skew_slop_secs),
    );
    push_line(&mut output, "");

    push_line(&mut output, "[security]");
    push_line(
        &mut output,
        &format!("mode = {}", toml_quote(knobs.security.name())),
    );
    match knobs.security {
        SecurityChoice::Enforced => {
            push_line(
                &mut output,
                "# GENERATED BOOTSTRAP SECRET: move this value into your secret manager before rollout.",
            );
            push_line(
                &mut output,
                &format!(
                    "cursor_hmac_key_hex = {}",
                    toml_quote(&random_hmac_key_hex())
                ),
            );
        }
        SecurityChoice::OpenUnsafe => {
            push_line(
                &mut output,
                "# WARNING: open_unsafe permits anonymous access and is only for isolated development.",
            );
        }
    }
    push_line(&mut output, "");

    push_line(&mut output, "# Runtime environment recommendations:");
    push_line(
        &mut output,
        &format!(
            "# ZEPPELIN_COMPACTION_WORKERS={} # applied: max(1, vCPU/4)",
            knobs.compaction_workers
        ),
    );
    push_line(
        &mut output,
        "# ZEPPELIN_QUERY_WORKERS and ZEPPELIN_RAYON_THREADS are parsed but not applied today.",
    );
    push_line(
        &mut output,
        "# ZEPPELIN_MAX_CLUSTERS_PER_OBJECT is a recall/cost-sensitive build dial; left unset.",
    );
    push_line(&mut output, "# Not tunable without a code change:");
    push_line(
        &mut output,
        "# - S3 retries=2, request timeout=30s, connection pool=64",
    );
    push_line(
        &mut output,
        "# - ReadPlan gap=64KiB, max request=8MiB, concurrency=8",
    );
    push_line(
        &mut output,
        &format!(
            "# - modeled aggregate object-store bandwidth per node: {:.2} MB/s",
            knobs.aggregate_mbps_per_node
        ),
    );
    output
}

/// Renders, loads, validates, and cross-checks a generated configuration.
///
/// # Errors
///
/// Returns [`EmitError::Config`] when the real loader rejects the TOML or
/// [`EmitError::IntentMismatch`] when a parsed value differs from the tuner.
pub fn render_and_validate(knobs: &TunedKnobs) -> Result<ValidatedConfig, EmitError> {
    let text = render_toml(knobs);
    let config = Config::load_from_str(&text)?;
    cross_check(&config, knobs)?;
    Ok(ValidatedConfig { text, config })
}

/// Writes an already validated configuration, refusing implicit overwrite.
///
/// # Errors
///
/// Returns [`EmitError::AlreadyExists`] if `path` exists without `force`, or
/// [`EmitError::Io`] for any open, write, or flush failure.
pub fn write_validated_config(
    path: &Path,
    rendered: &ValidatedConfig,
    force: bool,
) -> Result<(), EmitError> {
    let mut options = OpenOptions::new();
    options.write(true);
    if force {
        options.create(true).truncate(true);
    } else {
        options.create_new(true);
    }
    let mut file = options.open(path).map_err(|source| {
        if !force && source.kind() == std::io::ErrorKind::AlreadyExists {
            EmitError::AlreadyExists {
                path: path.to_path_buf(),
            }
        } else {
            EmitError::Io {
                path: path.to_path_buf(),
                source,
            }
        }
    })?;
    file.write_all(rendered.text.as_bytes())
        .and_then(|()| file.sync_all())
        .map_err(|source| EmitError::Io {
            path: path.to_path_buf(),
            source,
        })
}

fn cross_check(config: &Config, knobs: &TunedKnobs) -> Result<(), EmitError> {
    check_equal(
        "cache.memory_cache_max_mb",
        config.cache.memory_cache_max_mb,
        knobs.memory_cache_max_mb,
    )?;
    check_equal(
        "gc.horizon_secs",
        config.gc.horizon_secs,
        knobs.gc_horizon_secs,
    )?;
    check_equal(
        "gc horizon floor",
        config.gc_horizon_floor_secs(),
        Some(knobs.gc_horizon_floor_secs),
    )?;
    check_equal(
        "indexing effective nlist",
        config.indexing.effective_num_centroids(knobs.shape.vectors),
        knobs.nlist,
    )?;
    check_equal(
        "indexing.quantization",
        config.indexing.quantization,
        knobs.quantization,
    )?;
    check_equal(
        "indexing.default_nprobe",
        config.indexing.default_nprobe,
        knobs.nprobe,
    )?;
    check_equal(
        "indexing.max_nprobe",
        config.indexing.max_nprobe,
        knobs.max_nprobe,
    )?;
    check_equal(
        "query.rerank_coalesce_gap_bytes",
        config.effective_rerank_coalesce_gap_bytes(),
        knobs.rerank_coalesce_gap_bytes,
    )?;
    check_equal(
        "storage.backend",
        config.storage.backend,
        storage_backend_value(knobs.cloud),
    )?;
    check_equal(
        "storage.bucket",
        config.storage.bucket.as_str(),
        knobs.bucket.as_str(),
    )?;
    let expected_security = match knobs.security {
        SecurityChoice::Enforced => SecurityMode::Enforced,
        SecurityChoice::OpenUnsafe => SecurityMode::OpenUnsafe,
    };
    check_equal("security.mode", config.security.mode, expected_security)
}

fn check_equal<T>(field: &str, actual: T, expected: T) -> Result<(), EmitError>
where
    T: std::fmt::Debug + PartialEq,
{
    if actual == expected {
        Ok(())
    } else {
        Err(EmitError::IntentMismatch {
            reason: format!("{field}: parsed {actual:?}, intended {expected:?}"),
        })
    }
}

fn storage_backend(cloud: Cloud) -> &'static str {
    match cloud {
        Cloud::Aws => "s3",
        Cloud::Gcp => "gcs",
        Cloud::Azure => "azure",
    }
}

fn storage_backend_value(cloud: Cloud) -> StorageBackend {
    match cloud {
        Cloud::Aws => StorageBackend::S3,
        Cloud::Gcp => StorageBackend::Gcs,
        Cloud::Azure => StorageBackend::Azure,
    }
}

fn quantization_name(quantization: QuantizationType) -> &'static str {
    match quantization {
        QuantizationType::None => "none",
        QuantizationType::Scalar => "scalar",
        QuantizationType::TwoBit => "two_bit",
        QuantizationType::Product => "product",
    }
}

fn random_hmac_key_hex() -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut bytes = [0u8; 32];
    OsRng.fill_bytes(&mut bytes);
    let mut output = String::with_capacity(64);
    for byte in bytes {
        output.push(char::from(HEX[usize::from(byte >> 4)]));
        output.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
    output
}

fn toml_quote(value: &str) -> String {
    toml::Value::String(value.to_string()).to_string()
}

fn push_line(output: &mut String, line: &str) {
    output.push_str(line);
    output.push('\n');
}

#[cfg(test)]
mod tests {
    use super::super::advisor::DataShape;
    use super::super::catalog::Catalog;
    use super::super::rows::Quantization;
    use super::super::tuner::{
        tune, CacheSelection, SafetyIntervals, SecurityChoice, TuningRequest,
    };
    use super::*;

    fn knobs() -> TunedKnobs {
        let catalog = Catalog::embedded();
        let instance = catalog
            .instance(Cloud::Aws, "i4i.2xlarge")
            .unwrap_or_else(|| panic!("missing i4i.2xlarge fixture"));
        tune(&TuningRequest {
            cloud: Cloud::Aws,
            region: "us-east-1",
            instance,
            replicas: 3,
            bucket: "example-bucket",
            shape: DataShape {
                vectors: 21_000_000,
                dims: 768,
                filters: true,
                fts: true,
            },
            quantization: Quantization::RabitqTwoBit,
            nprobe: 256,
            cache: CacheSelection::Nvme {
                capacity_gb: instance.nvme_gb,
            },
            predicted_p99_ms: 250.0,
            security: SecurityChoice::Enforced,
            safety: SafetyIntervals::default(),
        })
        .unwrap_or_else(|error| panic!("tuning failed: {error}"))
    }

    #[test]
    fn enforced_render_generates_fresh_valid_secrets() {
        let knobs = knobs();
        let first = render_and_validate(&knobs)
            .unwrap_or_else(|error| panic!("first render failed: {error}"));
        let second = render_and_validate(&knobs)
            .unwrap_or_else(|error| panic!("second render failed: {error}"));
        assert_ne!(first.text(), second.text());
        let document: toml::Value = toml::from_str(first.text())
            .unwrap_or_else(|error| panic!("rendered TOML failed to parse: {error}"));
        let key = document["security"]["cursor_hmac_key_hex"]
            .as_str()
            .unwrap_or_else(|| panic!("render omitted cursor key"));
        assert_eq!(key.len(), 64);
        assert!(key.bytes().all(|byte| byte.is_ascii_hexdigit()));
    }

    #[test]
    fn writer_refuses_existing_file_without_force() {
        let rendered =
            render_and_validate(&knobs()).unwrap_or_else(|error| panic!("render failed: {error}"));
        let directory =
            tempfile::tempdir().unwrap_or_else(|error| panic!("failed to create tempdir: {error}"));
        let path = directory.path().join("zeppelin.toml");
        write_validated_config(&path, &rendered, false)
            .unwrap_or_else(|error| panic!("initial write failed: {error}"));
        let error = write_validated_config(&path, &rendered, false)
            .err()
            .unwrap_or_else(|| panic!("second write unexpectedly succeeded"));
        assert!(matches!(error, EmitError::AlreadyExists { .. }));
        write_validated_config(&path, &rendered, true)
            .unwrap_or_else(|error| panic!("forced write failed: {error}"));
    }
}
