//! Shared data vocabulary for Zeppelin's public and internal boundaries.
//!
//! This module defines the small, serializable types that let the HTTP layer,
//! WAL, immutable segments, index implementations, and query engine agree on
//! what a vector, filter, result, and search policy mean. It deliberately owns
//! data shapes rather than behavior: distance computation lives in
//! [`crate::index::distance`], filter evaluation lives in
//! [`crate::index::filter`] and [`crate::index::bitmap`], and consistency is
//! enforced by [`crate::query`]. No item in this file performs I/O or decides
//! which S3 objects are authoritative.
//!
//! ```text
//! HTTP request / library caller
//!             |
//!             | VectorEntry, Filter, ConsistencyLevel
//!             v
//!       WAL and immutable segments
//!             |
//!             | DistanceMetric and IndexType guide execution
//!             v
//!        index + query engine
//!             |
//!             | SearchResult
//!             v
//!          HTTP response
//! ```
//!
//! The important compatibility invariant is that the Serde representation is
//! part of Zeppelin's stored-data and API contract. Renaming a variant, adding
//! a tag, changing whether `None` is omitted, or reordering variants of the
//! untagged [`crate::types::AttributeValue`] can change which existing JSON
//! payloads decode. In particular, any serialization tree containing
//! [`crate::types::AttributeValue`] or a
//! `skip_serializing_if` field must use a self-describing format such as JSON or
//! MessagePack, not bincode.
//!
//! ## Reading map
//!
//! 1. Start with [`crate::types::VectorId`], [`crate::types::VectorEntry`], and
//!    [`crate::types::SearchResult`] for the records that enter and leave
//!    retrieval.
//! 2. Read [`crate::types::DistanceMetric`] and [`crate::types::IndexType`] for
//!    namespace-level search choices.
//! 3. Read [`crate::types::AttributeValue`] and the recursive
//!    [`crate::types::Filter`] expression tree for metadata filtering.
//! 4. Finish with [`crate::types::ConsistencyLevel`] to understand how
//!    compacted segments and uncompacted WAL fragments contribute to a read.
//!
//! ## Rust concepts used here
//!
//! Rust enums combine the role of Java sealed hierarchies with the compact
//! tagged-union style familiar from C. Pattern matching forces consumers to
//! consider every variant when they do not use a wildcard.
//! [`crate::types::Filter::Not`] stores its recursive child in a
//! [`std::boxed::Box`]: the heap indirection gives the enum a finite size, like
//! a C AST node containing a pointer, while ownership makes the child non-null
//! and ensures it is freed automatically. `Option<T>` makes absence explicit
//! rather than using Java `null` or a C sentinel value.
//!
//! The `Serialize` and `Deserialize` implementations are generated by derive
//! macros. These macros add compile-time code; they do not use Java-style
//! runtime reflection. The `Clone` derives perform owned copies when a caller
//! requests one, whereas shared borrows such as `&Filter` allocate and copy
//! nothing.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// A caller-chosen identifier for a vector within one namespace.
///
/// IDs are unique only inside their namespace and are used to replace, fetch,
/// or tombstone a logical vector across WAL fragments and compacted segments.
/// This is currently a type alias, so it documents intent but does not prevent
/// an arbitrary [`String`] from being passed where a vector ID is expected.
///
/// # Example
///
/// The ID `"product-42"` can refer to one vector in namespace `catalog-us`
/// and a different vector in namespace `catalog-eu`.
///
/// # Rust Notes for Java/C Engineers
///
/// Unlike a Java wrapper class or a C struct containing a character pointer,
/// this alias has exactly the same type and runtime representation as
/// [`String`]. It adds vocabulary without adding validation or allocation.
pub type VectorId = String;

/// Selects how Zeppelin converts two vectors into a sortable distance.
///
/// The implementations in [`crate::index::distance`] preserve the query
/// engine's central ordering rule: **smaller values are closer**, including for
/// dot product, which is negated. Namespace metadata chooses one metric and
/// callers must use that same metric when building and querying its index.
///
/// # Example
///
/// A namespace configured with [`DistanceMetric::Cosine`] ranks vectors by
/// direction rather than magnitude; [`DistanceMetric::Euclidean`] ranks by
/// squared straight-line distance.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DistanceMetric {
    /// Cosine distance, computed as one minus cosine similarity.
    Cosine,
    /// Squared Euclidean (L2) distance; omitting the square root preserves rank order.
    Euclidean,
    /// Negated dot-product similarity so that the closest result still sorts first.
    DotProduct,
}

impl std::fmt::Display for DistanceMetric {
    /// Writes the metric's stable snake-case name.
    ///
    /// # Parameters
    ///
    /// - `f`: Destination formatter supplied by Rust's formatting machinery.
    ///
    /// # Returns
    ///
    /// Returns formatting success; writing to the formatter is the only
    /// possible source of failure.
    ///
    /// # Example
    ///
    /// [`DistanceMetric::DotProduct`] is displayed as `"dot_product"`, matching
    /// its JSON spelling.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DistanceMetric::Cosine => write!(f, "cosine"),
            DistanceMetric::Euclidean => write!(f, "euclidean"),
            DistanceMetric::DotProduct => write!(f, "dot_product"),
        }
    }
}

/// A typed metadata value attached to a [`VectorEntry`].
///
/// Scalar values support equality and numeric range predicates. List values
/// support membership predicates. Text token predicates operate on
/// [`AttributeValue::String`] values. The exact comparison rules are defined by
/// [`crate::index::filter`], while [`crate::index::bitmap`] can preselect rows
/// for supported predicates before exact evaluation.
///
/// This enum is `#[serde(untagged)]`: JSON contains the value itself, such as
/// `"blue"`, `42`, or `["sale", "summer"]`, rather than an explicit variant
/// name. That keeps the API natural but requires a self-describing serializer
/// and makes variant order part of deserialization compatibility.
///
/// # Example
///
/// A product can store `color = String("blue")`, `price = Float(19.95)`, and
/// `tags = StringList(["sale", "summer"])`; a [`Filter`] can then compare or
/// search those fields without interpreting raw JSON inside the query engine.
///
/// # Rust Notes for Java/C Engineers
///
/// Each enum variant carries only the data valid for that case. This resembles
/// a Java sealed interface with record implementations, or a C tagged union,
/// but Rust keeps the tag and payload consistent and requires owned `String`
/// and `Vec` values to be freed automatically when the enum is dropped.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AttributeValue {
    /// A single owned UTF-8 string.
    String(String),
    /// A single 64-bit signed integer.
    Integer(i64),
    /// A single 64-bit floating-point number.
    Float(f64),
    /// A Boolean flag.
    Bool(bool),
    /// An ordered list of owned UTF-8 strings, commonly used for tags.
    StringList(Vec<String>),
    /// An ordered list of 64-bit signed integers.
    IntegerList(Vec<i64>),
    /// An ordered list of 64-bit floating-point numbers.
    FloatList(Vec<f64>),
}

/// One logical vector supplied to Zeppelin's write and index paths.
///
/// [`crate::server::handlers::vectors`] accepts entries from clients,
/// [`crate::wal`] records them in immutable fragments, and index builders later
/// compact them into immutable segments. This type does not validate dimension,
/// finite floating-point values, ID uniqueness, or attribute limits; callers at
/// the API and domain boundaries perform those checks before publication.
///
/// # Example
///
/// A catalog upsert can carry ID `"product-42"`, embedding
/// `[0.12, -0.30, 0.91]`, and attributes such as `color = "blue"`. A later
/// upsert with the same ID replaces the logical record once its WAL fragment is
/// published through the authoritative manifest.
///
/// # Rust Notes for Java/C Engineers
///
/// Every field is owned: moving a `VectorEntry` transfers its `String`, vector
/// allocation, and attribute map without copying their contents. Callers can
/// explicitly `clone` when they need a deep owned copy. In Java those buffers
/// would normally be shared through references; in C their allocation and
/// cleanup ownership would need a separate convention.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VectorEntry {
    /// Caller-chosen identity used for upsert, lookup, deduplication, and deletion.
    pub id: VectorId,
    /// Dense `f32` coordinates whose length must equal the namespace dimension.
    pub values: Vec<f32>,
    /// Optional field map used by filters, facets, full-text search, and projection.
    ///
    /// `None` means that the record has no attribute object and is omitted from
    /// JSON. `Some(empty_map)` is an explicitly present but empty object.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attributes: Option<HashMap<String, AttributeValue>>,
}

/// One ranked result returned by vector, lexical, or hybrid retrieval.
///
/// The meaning and direction of [`SearchResult::score`] depend on the executed
/// retrieval path: vector search returns a distance where lower is better,
/// BM25 returns a relevance score where higher is better, and fusion may return
/// a normalized contribution. Consumers must interpret the score together with
/// the query they submitted rather than comparing scores from different modes.
///
/// # Example
///
/// A cosine query can return `product-42` with distance `0.03`; the same ID in a
/// BM25 query can have a positive lexical score with an unrelated scale.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchResult {
    /// Identity of the live vector selected by retrieval and WAL merge rules.
    pub id: VectorId,
    /// Path-specific ranking value; see the type-level documentation for direction.
    pub score: f32,
    /// Projected metadata when the caller requested attributes, otherwise `None`.
    ///
    /// Unlike [`VectorEntry::attributes`], a missing value serializes as JSON
    /// `null` because this field is not skipped.
    #[serde(default)]
    pub attributes: Option<HashMap<String, AttributeValue>>,
}

/// A recursive predicate over vector attributes.
///
/// Filters enter through the query API, may be converted into bitmap candidate
/// sets, and are evaluated exactly against stored attributes before a result is
/// returned. Positive predicates generally do not match a missing field;
/// negative predicates such as [`Filter::NotEq`] and [`Filter::NotIn`] do. An
/// empty [`Filter::And`] is true and an empty [`Filter::Or`] is false under the
/// current iterator-based evaluator.
///
/// The JSON representation uses an `op` discriminator. For example:
///
/// ```text
/// {"op":"and","filters":[
///   {"op":"eq","field":"color","value":"blue"},
///   {"op":"range","field":"price","gte":10.0,"lt":20.0}
/// ]}
/// ```
///
/// # Rust Notes for Java/C Engineers
///
/// This is an owned abstract syntax tree. `Vec<Filter>` owns multiple children;
/// [`Box<Filter>`] owns one heap-allocated child for logical NOT. Java would
/// normally represent this with an interface hierarchy and object references;
/// C would use a tagged union plus manually managed child pointers. Rust's enum
/// makes the set of operations closed and frees the full tree through RAII.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case", deny_unknown_fields)]
pub enum Filter {
    /// Matches when the named field equals the supplied value under attribute comparison rules.
    Eq {
        /// Attribute key to look up on each candidate vector.
        field: String,
        /// Typed value to compare with the stored attribute.
        value: AttributeValue,
    },
    /// Matches when the field is absent or does not equal the supplied value.
    #[serde(rename = "not_eq")]
    NotEq {
        /// Attribute key to look up on each candidate vector.
        field: String,
        /// Typed value that must not equal the stored attribute.
        value: AttributeValue,
    },
    /// Matches a numeric field against any supplied inclusive or exclusive bounds.
    Range {
        /// Attribute key whose integer or float value is compared.
        field: String,
        /// Inclusive lower bound, or no inclusive lower bound when `None`.
        #[serde(skip_serializing_if = "Option::is_none")]
        gte: Option<f64>,
        /// Inclusive upper bound, or no inclusive upper bound when `None`.
        #[serde(skip_serializing_if = "Option::is_none")]
        lte: Option<f64>,
        /// Exclusive lower bound, or no exclusive lower bound when `None`.
        #[serde(skip_serializing_if = "Option::is_none")]
        gt: Option<f64>,
        /// Exclusive upper bound, or no exclusive upper bound when `None`.
        #[serde(skip_serializing_if = "Option::is_none")]
        lt: Option<f64>,
    },
    /// Matches when at least one supplied value equals the stored field.
    In {
        /// Attribute key to look up on each candidate vector.
        field: String,
        /// Candidate values; order is not semantically significant.
        values: Vec<AttributeValue>,
    },
    /// Matches when the field is absent or no supplied value equals it.
    #[serde(rename = "not_in")]
    NotIn {
        /// Attribute key to look up on each candidate vector.
        field: String,
        /// Values that disqualify a candidate; order is not significant.
        values: Vec<AttributeValue>,
    },
    /// Logical conjunction that requires every child predicate to match.
    And {
        /// Owned child predicates; an empty list is vacuously true.
        filters: Vec<Filter>,
    },
    /// Logical disjunction that requires at least one child predicate to match.
    Or {
        /// Owned child predicates; an empty list is false.
        filters: Vec<Filter>,
    },
    /// Logical negation of one child predicate.
    Not {
        /// Heap-owned child; boxing makes the recursive enum a fixed-size value.
        filter: Box<Filter>,
    },
    /// Matches list membership, or substring containment for two string values.
    Contains {
        /// Attribute key to look up on each candidate vector.
        field: String,
        /// Element or substring that must be contained by the stored value.
        value: AttributeValue,
    },
    /// Matches when every query token occurs in a tokenized string field, in any order.
    ContainsAllTokens {
        /// Attribute key whose stored value must be a string.
        field: String,
        /// Query text pieces tokenized with the default FTS field configuration.
        tokens: Vec<String>,
    },
    /// Matches when tokenized query terms appear adjacently and in order.
    ContainsTokenSequence {
        /// Attribute key whose stored value must be a string.
        field: String,
        /// Query text pieces tokenized and then matched as one ordered sequence.
        tokens: Vec<String>,
    },
}

/// Chooses how a read combines authoritative compacted state with recent WAL state.
///
/// Both modes resolve visibility from the manifest in object storage. The
/// difference is how much uncompacted WAL work the query performs after loading
/// that manifest. [`ConsistencyLevel::Strong`] is the default because it shows
/// all committed writes; [`ConsistencyLevel::Eventual`] reduces read work while
/// still honoring tombstones so deleted data is not resurrected.
///
/// ```text
/// authoritative manifest
///          |
///          +--> compacted segments --------------------+
///          |                                           |
///          +--> uncompacted WAL upserts -- Strong -----+--> visible read
///          |                                           |
///          +--> uncompacted WAL tombstones -- both ----+
/// ```
///
/// # Example
///
/// If vector `new-7` was just committed to the WAL but has not been compacted,
/// a strong query can return it while an eventual query may not. If `old-2` was
/// just tombstoned, neither mode should return the deleted record.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConsistencyLevel {
    /// Searches compacted segments and scans uncompacted WAL upserts and tombstones.
    #[default]
    Strong,
    /// Searches compacted segments and WAL tombstones, but may miss recent upserts or updates.
    Eventual,
}

/// Declares whether smaller or larger native source scores rank first.
///
/// ANN distances are lower-is-better. BM25 relevance and late-interaction
/// MaxSim remain higher-is-better. Carrying this explicitly prevents fusion,
/// pagination, and provenance code from guessing from request shape.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ScoreDirection {
    /// Smaller native scores rank ahead of larger scores.
    LowerIsBetter,
    /// Larger native scores rank ahead of smaller scores.
    HigherIsBetter,
}

/// Selects the vector-index family and compression strategy for a namespace.
///
/// All variants use approximate nearest-neighbor search and trade storage,
/// memory, CPU, and recall differently. The namespace's configured choice must
/// agree with the immutable segment artifacts the query engine loads.
///
/// # Example
///
/// [`IndexType::IvfFlat`] keeps full vectors for straightforward scoring, while
/// [`IndexType::IvfPq`] stores compact product-quantized codes when reducing
/// object size is worth additional approximation.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IndexType {
    /// Inverted-file index whose clusters retain uncompressed vectors.
    #[default]
    IvfFlat,
    /// Inverted-file index with scalar-quantized vector coordinates.
    IvfSq,
    /// Inverted-file index with product-quantized vector codes.
    IvfPq,
    /// Approximate index that navigates a multi-level centroid tree.
    Hierarchical,
    /// Fixed-dimensional candidate retrieval with token-level late reranking.
    LateInteractionFde,
}

#[allow(clippy::unwrap_used, clippy::expect_used)]
#[cfg(test)]
/// Regression tests for the JSON spellings and defaults that form the API contract.
mod tests {
    use super::*;

    /// Verifies that every distance metric round-trips through its stable JSON name.
    #[test]
    fn test_distance_metric_serde_roundtrip() {
        for (variant, expected_json) in [
            (DistanceMetric::Cosine, "\"cosine\""),
            (DistanceMetric::Euclidean, "\"euclidean\""),
            (DistanceMetric::DotProduct, "\"dot_product\""),
        ] {
            let json = serde_json::to_string(&variant).unwrap();
            assert_eq!(json, expected_json);
            let back: DistanceMetric = serde_json::from_str(&json).unwrap();
            assert_eq!(back, variant);
        }
    }

    #[test]
    fn unknown_index_type_fails_loudly() {
        let error = serde_json::from_str::<IndexType>("\"future_index\"")
            .expect_err("unknown index type must not decode");
        assert!(error.to_string().contains("unknown variant"));
    }

    /// Verifies that display output matches the metric names used in JSON and diagnostics.
    #[test]
    fn test_distance_metric_display() {
        assert_eq!(DistanceMetric::Cosine.to_string(), "cosine");
        assert_eq!(DistanceMetric::Euclidean.to_string(), "euclidean");
        assert_eq!(DistanceMetric::DotProduct.to_string(), "dot_product");
    }

    /// Verifies representative scalar and list values survive untagged JSON round-trips.
    #[test]
    fn test_attribute_value_serde_roundtrip() {
        let cases: Vec<(AttributeValue, &str)> = vec![
            (AttributeValue::String("hello".into()), "\"hello\""),
            (AttributeValue::Integer(42), "42"),
            (AttributeValue::Float(1.23), "1.23"),
            (AttributeValue::Bool(true), "true"),
            (
                AttributeValue::StringList(vec!["a".into(), "b".into()]),
                "[\"a\",\"b\"]",
            ),
        ];
        for (val, expected_json) in cases {
            let json = serde_json::to_string(&val).unwrap();
            assert_eq!(json, expected_json);
            let back: AttributeValue = serde_json::from_str(&json).unwrap();
            assert_eq!(back, val);
        }
    }

    /// Verifies a vector entry retains each attribute type across JSON serialization.
    #[test]
    fn test_vector_entry_serde_with_attributes() {
        let mut attrs = HashMap::new();
        attrs.insert("color".into(), AttributeValue::String("red".into()));
        attrs.insert("count".into(), AttributeValue::Integer(5));
        let entry = VectorEntry {
            id: "vec-1".into(),
            values: vec![1.0, 2.0, 3.0],
            attributes: Some(attrs),
        };
        let json = serde_json::to_string(&entry).unwrap();
        let back: VectorEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(back.id, "vec-1");
        assert_eq!(back.values, vec![1.0, 2.0, 3.0]);
        assert!(back.attributes.is_some());
        let back_attrs = back.attributes.unwrap();
        assert_eq!(
            back_attrs.get("color"),
            Some(&AttributeValue::String("red".into()))
        );
        assert_eq!(back_attrs.get("count"), Some(&AttributeValue::Integer(5)));
    }

    /// Verifies absent vector attributes are omitted on write and restored as `None`.
    #[test]
    fn test_vector_entry_serde_without_attributes() {
        let entry = VectorEntry {
            id: "vec-2".into(),
            values: vec![0.5],
            attributes: None,
        };
        let json = serde_json::to_string(&entry).unwrap();
        assert!(!json.contains("attributes"));
        let back: VectorEntry = serde_json::from_str(&json).unwrap();
        assert!(back.attributes.is_none());
    }

    /// Verifies representative filter AST nodes use the documented `op` discriminator.
    #[test]
    fn test_filter_serde_tagged() {
        // Eq
        let eq = Filter::Eq {
            field: "color".into(),
            value: AttributeValue::String("blue".into()),
        };
        let json = serde_json::to_string(&eq).unwrap();
        assert!(json.contains("\"op\":\"eq\""));
        let back: Filter = serde_json::from_str(&json).unwrap();
        match back {
            Filter::Eq { field, value } => {
                assert_eq!(field, "color");
                assert_eq!(value, AttributeValue::String("blue".into()));
            }
            _ => panic!("expected Eq"),
        }

        // Range
        let range = Filter::Range {
            field: "price".into(),
            gte: Some(10.0),
            lte: Some(100.0),
            gt: None,
            lt: None,
        };
        let json = serde_json::to_string(&range).unwrap();
        assert!(json.contains("\"op\":\"range\""));
        assert!(!json.contains("\"gt\""));
        assert!(!json.contains("\"lt\""));
        let back: Filter = serde_json::from_str(&json).unwrap();
        match back {
            Filter::Range {
                field, gte, lte, ..
            } => {
                assert_eq!(field, "price");
                assert_eq!(gte, Some(10.0));
                assert_eq!(lte, Some(100.0));
            }
            _ => panic!("expected Range"),
        }

        // In
        let in_filter = Filter::In {
            field: "tag".into(),
            values: vec![
                AttributeValue::String("a".into()),
                AttributeValue::String("b".into()),
            ],
        };
        let json = serde_json::to_string(&in_filter).unwrap();
        assert!(json.contains("\"op\":\"in\""));
        let back: Filter = serde_json::from_str(&json).unwrap();
        match back {
            Filter::In { field, values } => {
                assert_eq!(field, "tag");
                assert_eq!(values.len(), 2);
            }
            _ => panic!("expected In"),
        }

        // And
        let and = Filter::And {
            filters: vec![eq.clone(), in_filter.clone()],
        };
        let json = serde_json::to_string(&and).unwrap();
        assert!(json.contains("\"op\":\"and\""));
        let back: Filter = serde_json::from_str(&json).unwrap();
        match back {
            Filter::And { filters } => assert_eq!(filters.len(), 2),
            _ => panic!("expected And"),
        }
    }

    /// Verifies omitted consistency settings select the strong-read path.
    #[test]
    fn test_consistency_level_default() {
        assert_eq!(ConsistencyLevel::default(), ConsistencyLevel::Strong);
    }

    /// Verifies omitted index settings select uncompressed IVF-Flat.
    #[test]
    fn test_index_type_default() {
        assert_eq!(IndexType::default(), IndexType::IvfFlat);
    }

    /// Verifies search-result attributes remain explicit JSON values, including `null`.
    #[test]
    fn test_search_result_serde() {
        // With attributes
        let mut attrs = HashMap::new();
        attrs.insert("tag".into(), AttributeValue::String("test".into()));
        let result = SearchResult {
            id: "vec-1".into(),
            score: 0.95,
            attributes: Some(attrs),
        };
        let json = serde_json::to_string(&result).unwrap();
        let back: SearchResult = serde_json::from_str(&json).unwrap();
        assert_eq!(back.id, "vec-1");
        assert_eq!(back.score, 0.95);
        assert!(back.attributes.is_some());

        // Without attributes
        let result = SearchResult {
            id: "vec-2".into(),
            score: 0.5,
            attributes: None,
        };
        let json = serde_json::to_string(&result).unwrap();
        assert!(json.contains("\"attributes\":null"));
        let back: SearchResult = serde_json::from_str(&json).unwrap();
        assert!(back.attributes.is_none());
    }

    // --- New filter operator serde tests ---

    /// Verifies inequality filters retain the explicit `not_eq` wire spelling.
    #[test]
    fn test_filter_not_eq_serde() {
        let f = Filter::NotEq {
            field: "status".into(),
            value: AttributeValue::String("deleted".into()),
        };
        let json = serde_json::to_string(&f).unwrap();
        assert!(json.contains("\"op\":\"not_eq\""));
        let back: Filter = serde_json::from_str(&json).unwrap();
        match back {
            Filter::NotEq { field, value } => {
                assert_eq!(field, "status");
                assert_eq!(value, AttributeValue::String("deleted".into()));
            }
            _ => panic!("expected NotEq"),
        }
    }

    /// Verifies set-exclusion filters retain the explicit `not_in` wire spelling.
    #[test]
    fn test_filter_not_in_serde() {
        let f = Filter::NotIn {
            field: "category".into(),
            values: vec![
                AttributeValue::String("spam".into()),
                AttributeValue::String("junk".into()),
            ],
        };
        let json = serde_json::to_string(&f).unwrap();
        assert!(json.contains("\"op\":\"not_in\""));
        let back: Filter = serde_json::from_str(&json).unwrap();
        match back {
            Filter::NotIn { field, values } => {
                assert_eq!(field, "category");
                assert_eq!(values.len(), 2);
            }
            _ => panic!("expected NotIn"),
        }
    }

    /// Verifies a logical OR retains both child predicates through JSON.
    #[test]
    fn test_filter_or_serde() {
        let f = Filter::Or {
            filters: vec![
                Filter::Eq {
                    field: "a".into(),
                    value: AttributeValue::Integer(1),
                },
                Filter::Eq {
                    field: "b".into(),
                    value: AttributeValue::Integer(2),
                },
            ],
        };
        let json = serde_json::to_string(&f).unwrap();
        assert!(json.contains("\"op\":\"or\""));
        let back: Filter = serde_json::from_str(&json).unwrap();
        match back {
            Filter::Or { filters } => assert_eq!(filters.len(), 2),
            _ => panic!("expected Or"),
        }
    }

    /// Verifies boxing a NOT child is transparent to the serialized filter tree.
    #[test]
    fn test_filter_not_serde() {
        let f = Filter::Not {
            filter: Box::new(Filter::Eq {
                field: "active".into(),
                value: AttributeValue::Bool(false),
            }),
        };
        let json = serde_json::to_string(&f).unwrap();
        assert!(json.contains("\"op\":\"not\""));
        let back: Filter = serde_json::from_str(&json).unwrap();
        match back {
            Filter::Not { filter } => match *filter {
                Filter::Eq { field, value } => {
                    assert_eq!(field, "active");
                    assert_eq!(value, AttributeValue::Bool(false));
                }
                _ => panic!("expected inner Eq"),
            },
            _ => panic!("expected Not"),
        }
    }

    /// Verifies containment filters preserve their field and typed needle.
    #[test]
    fn test_filter_contains_serde() {
        let f = Filter::Contains {
            field: "tags".into(),
            value: AttributeValue::String("rust".into()),
        };
        let json = serde_json::to_string(&f).unwrap();
        assert!(json.contains("\"op\":\"contains\""));
        let back: Filter = serde_json::from_str(&json).unwrap();
        match back {
            Filter::Contains { field, value } => {
                assert_eq!(field, "tags");
                assert_eq!(value, AttributeValue::String("rust".into()));
            }
            _ => panic!("expected Contains"),
        }
    }

    // --- New attribute type serde tests ---

    /// Verifies integer-list attributes remain integer lists after untagged decoding.
    #[test]
    fn test_integer_list_serde() {
        let val = AttributeValue::IntegerList(vec![1, 2, 3]);
        let json = serde_json::to_string(&val).unwrap();
        assert_eq!(json, "[1,2,3]");
        let back: AttributeValue = serde_json::from_str(&json).unwrap();
        assert_eq!(back, val);
    }

    /// Verifies float-list attributes remain float lists after untagged decoding.
    #[test]
    fn test_float_list_serde() {
        let val = AttributeValue::FloatList(vec![1.5, 2.5]);
        let json = serde_json::to_string(&val).unwrap();
        assert_eq!(json, "[1.5,2.5]");
        let back: AttributeValue = serde_json::from_str(&json).unwrap();
        assert_eq!(back, val);
    }

    /// Verifies every index family round-trips through its stable snake-case name.
    #[test]
    fn test_index_type_serde_roundtrip() {
        for (variant, expected) in [
            (IndexType::IvfFlat, "\"ivf_flat\""),
            (IndexType::IvfSq, "\"ivf_sq\""),
            (IndexType::IvfPq, "\"ivf_pq\""),
            (IndexType::Hierarchical, "\"hierarchical\""),
        ] {
            let json = serde_json::to_string(&variant).unwrap();
            assert_eq!(json, expected);
            let back: IndexType = serde_json::from_str(&json).unwrap();
            assert_eq!(back, variant);
        }
    }
}
